// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiW4zDs34XnRQkXa0sh1DZdrsr8dBrV00',
    appId: '1:567915614715:web:ef3a774a68716676197b5e',
    messagingSenderId: '567915614715',
    projectId: 'moghtareb-46dc4',
    authDomain: 'moghtareb-46dc4.firebaseapp.com',
    storageBucket: 'moghtareb-46dc4.appspot.com',
    measurementId: 'G-B99D8Z9PYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhjih2RmVlufz3Mj7fEE5OYihAPOnUjQ',
    appId: '1:567915614715:android:a0a9a29163d94c59197b5e',
    messagingSenderId: '567915614715',
    projectId: 'moghtareb-46dc4',
    storageBucket: 'moghtareb-46dc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7gjiVKnnsFKAHnMP-VHiO2JHzCpwzUY',
    appId: '1:567915614715:ios:d1c14d07190bc6c1197b5e',
    messagingSenderId: '567915614715',
    projectId: 'moghtareb-46dc4',
    storageBucket: 'moghtareb-46dc4.appspot.com',
    iosBundleId: 'com.example.moghtareb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7gjiVKnnsFKAHnMP-VHiO2JHzCpwzUY',
    appId: '1:567915614715:ios:b5d578b5fad03192197b5e',
    messagingSenderId: '567915614715',
    projectId: 'moghtareb-46dc4',
    storageBucket: 'moghtareb-46dc4.appspot.com',
    iosBundleId: 'com.example.moghtareb.RunnerTests',
  );
}
